global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]

  - job_name: 'mysql'
    static_configs:
      - targets: [ '172.17.0.1:9104' ]
        labels:
          instance: 'MySQL-Database'

  - job_name: 'api-gateway-service'
    metrics_path: '/api-gateway/actuator/prometheus'
    static_configs:
      - targets: [ '172.17.0.1:8080' ]
        labels:
          instance: 'Api-Gateway-Service'
          application: 'Api-Gateway-Service'

  - job_name: 'patient-service'
    metrics_path: '/patients/actuator/prometheus'
    static_configs:
      - targets: [ '172.17.0.1:8080' ]
        labels:
          instance: 'Patient-Service'
          application: 'Patient-Service'
